# 参数管理

In [2]:
import torch 
from torch import nn
net = nn.Sequential(nn.Linear(4, 8), nn.ReLU(), nn.Linear(8, 1))
X = torch.rand(size=(2, 4))
net(X)

tensor([[0.0857],
        [0.0425]], grad_fn=<AddmmBackward0>)

## 参数访问

In [6]:
print(net[0].state_dict())

OrderedDict([('weight', tensor([[-0.4131,  0.0943, -0.0111,  0.4869],
        [ 0.3296, -0.2672,  0.0235, -0.2074],
        [-0.2811,  0.3392,  0.0873, -0.3910],
        [-0.2205,  0.1741, -0.0282, -0.2346],
        [-0.0859, -0.0100,  0.1987, -0.0302],
        [-0.2056,  0.2822,  0.2234,  0.4887],
        [-0.2141,  0.2437, -0.0034, -0.4903],
        [ 0.4999, -0.1810, -0.4289, -0.4515]])), ('bias', tensor([-0.0076,  0.3712, -0.1637,  0.0526, -0.4333,  0.4918,  0.1700,  0.3688]))])


In [11]:
print(net[0].weight.data)
print(net[0].bias)

tensor([[-0.4131,  0.0943, -0.0111,  0.4869],
        [ 0.3296, -0.2672,  0.0235, -0.2074],
        [-0.2811,  0.3392,  0.0873, -0.3910],
        [-0.2205,  0.1741, -0.0282, -0.2346],
        [-0.0859, -0.0100,  0.1987, -0.0302],
        [-0.2056,  0.2822,  0.2234,  0.4887],
        [-0.2141,  0.2437, -0.0034, -0.4903],
        [ 0.4999, -0.1810, -0.4289, -0.4515]])
Parameter containing:
tensor([-0.0076,  0.3712, -0.1637,  0.0526, -0.4333,  0.4918,  0.1700,  0.3688],
       requires_grad=True)


In [16]:
print(net[0].weight.grad)

None


In [20]:
for name,param in net[0].named_parameters():
    print(name,":",param)

weight : Parameter containing:
tensor([[-0.4131,  0.0943, -0.0111,  0.4869],
        [ 0.3296, -0.2672,  0.0235, -0.2074],
        [-0.2811,  0.3392,  0.0873, -0.3910],
        [-0.2205,  0.1741, -0.0282, -0.2346],
        [-0.0859, -0.0100,  0.1987, -0.0302],
        [-0.2056,  0.2822,  0.2234,  0.4887],
        [-0.2141,  0.2437, -0.0034, -0.4903],
        [ 0.4999, -0.1810, -0.4289, -0.4515]], requires_grad=True)
bias : Parameter containing:
tensor([-0.0076,  0.3712, -0.1637,  0.0526, -0.4333,  0.4918,  0.1700,  0.3688],
       requires_grad=True)
